title: Tods Arxiv Daily Paper
description: Automatically Update Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true
#theme: jekyll-theme-slate

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 

github:
  zip_url: https://github.com/bansky-cl/tods-arxiv-daily-paper
  another_url: https://github.com/bansky-cl/tods-arxiv-daily-paper
